DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS music;
DROP TABLE IF EXISTS playlists;

CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY,
    user_first_name VARCHAR(255) NOT NULL,
    user_last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    subscription_type VARCHAR(20) NOT NULL CHECK (subscription_type  IN ('free', 'premium'))
);

CREATE TABLE IF NOT EXISTS music (
    song_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    song_title VARCHAR(255) NOT NULL,
    genre VARCHAR(50) NOT NULL CHECK (
        genre IN ('Pop', 'Rock', 'Hip-hop', 'Jazz', 'Classical music')
    ),
    description TEXT
);

CREATE TABLE IF NOT EXISTS playlists (
    playlist_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    added_date DATE NOT NULL,
    user_id UUID,
    song_id INTEGER,
    CONSTRAINT fk_playlists_users
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_playlist_songs
        FOREIGN KEY (song_id) REFERENCES music(song_id)
);
